There are many datasets we can use from this database. For example, the age and sex information can be retrieved in this way: **Income**

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
income = pd.read_csv('/content/drive/MyDrive/capstone_yb/Voting ML/DATA/WA_Income.csv')
 # WA 2020, INCOME
income.head()# WA 2020, INCOME

,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to $14,999","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to $24,999",...,Estimate!!Nonfamily households!!Median income (dollars),Margin of Error!!Nonfamily households!!Median income (dollars),Estimate!!Nonfamily households!!Mean income (dollars),Margin of Error!!Nonfamily households!!Mean income (dollars),Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
0,1400000US53001950100,"Census Tract 9501, Adams County, Washington",1099,100,7.6,3,6.2,3.2,9,2.6,...,27684,5056,44910,14147,(X),(X),(X),(X),34.2,(X)
1,1400000US53001950200,"Census Tract 9502, Adams County, Washington",612,97,8.8,5.2,3.3,2,6.4,3.3,...,22679,13082,35755,12429,(X),(X),(X),(X),38.4,(X)
2,1400000US53001950301,"Census Tract 9503.01, Adams County, Washington",501,92,9,8.3,0,7.2,18.2,14.5,...,-,**,71912,42512,(X),(X),(X),(X),36.3,(X)
3,1400000US53001950302,"Census Tract 9503.02, Adams County, Washington",621,123,0,5.9,6.4,7.9,13.2,11.8,...,21611,6147,26252,7142,(X),(X),(X),(X),19.5,(X)
4,1400000US53001950303,"Census Tract 9503.03, Adams County, Washington",632,122,1.4,2.5,0,5.8,21.4,12.4,...,28458,3574,29666,5063,(X),(X),(X),(X),67.7,(X)

In [4]:
for column in income.columns:
    print(column)#130 columns!!!

Geography
Geographic Area Name
Estimate!!Households!!Total
Margin of Error!!Households!!Total
Estimate!!Households!!Total!!Less than $10,000
Margin of Error!!Households!!Total!!Less than $10,000
Estimate!!Households!!Total!!$10,000 to $14,999
Margin of Error!!Households!!Total!!$10,000 to $14,999
Estimate!!Households!!Total!!$15,000 to $24,999
Margin of Error!!Households!!Total!!$15,000 to $24,999
Estimate!!Households!!Total!!$25,000 to $34,999
Margin of Error!!Households!!Total!!$25,000 to $34,999
Estimate!!Households!!Total!!$35,000 to $49,999
Margin of Error!!Households!!Total!!$35,000 to $49,999
Estimate!!Households!!Total!!$50,000 to $74,999
Margin of Error!!Households!!Total!!$50,000 to $74,999
Estimate!!Households!!Total!!$75,000 to $99,999
Margin of Error!!Households!!Total!!$75,000 to $99,999
Estimate!!Households!!Total!!$100,000 to $149,999
Margin of Error!!Households!!Total!!$100,000 to $149,999
Estimate!!Households!!Total!!$150,000 to $199,999
Margin of Error!!Households!!Total!!$150,000 to $199,999
Estimate!!Households!!Total!!$200,000 or more
Margin of Error!!Households!!Total!!$200,000 or more
Estimate!!Households!!Median income (dollars)
Margin of Error!!Households!!Median income (dollars)
Estimate!!Households!!Mean income (dollars)
Margin of Error!!Households!!Mean income (dollars)
Estimate!!Households!!PERCENT ALLOCATED!!Household income in the past 12 months
Margin of Error!!Households!!PERCENT ALLOCATED!!Household income in the past 12 months
Estimate!!Households!!PERCENT ALLOCATED!!Family income in the past 12 months
Margin of Error!!Households!!PERCENT ALLOCATED!!Family income in the past 12 months
Estimate!!Households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
Margin of Error!!Households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
Estimate!!Families!!Total
Margin of Error!!Families!!Total
Estimate!!Families!!Total!!Less than $10,000
Margin of Error!!Families!!Total!!Less than $10,000
Estimate!!Families!!Total!!$10,000 to $14,999
Margin of Error!!Families!!Total!!$10,000 to $14,999
Estimate!!Families!!Total!!$15,000 to $24,999
Margin of Error!!Families!!Total!!$15,000 to $24,999
Estimate!!Families!!Total!!$25,000 to $34,999
Margin of Error!!Families!!Total!!$25,000 to $34,999
Estimate!!Families!!Total!!$35,000 to $49,999
Margin of Error!!Families!!Total!!$35,000 to $49,999
Estimate!!Families!!Total!!$50,000 to $74,999
Margin of Error!!Families!!Total!!$50,000 to $74,999
Estimate!!Families!!Total!!$75,000 to $99,999
Margin of Error!!Families!!Total!!$75,000 to $99,999
Estimate!!Families!!Total!!$100,000 to $149,999
Margin of Error!!Families!!Total!!$100,000 to $149,999
Estimate!!Families!!Total!!$150,000 to $199,999
Margin of Error!!Families!!Total!!$150,000 to $199,999
Estimate!!Families!!Total!!$200,000 or more
Margin of Error!!Families!!Total!!$200,000 or more
Estimate!!Families!!Median income (dollars)
Margin of Error!!Families!!Median income (dollars)
Estimate!!Families!!Mean income (dollars)
Margin of Error!!Families!!Mean income (dollars)
Estimate!!Families!!PERCENT ALLOCATED!!Household income in the past 12 months
Margin of Error!!Families!!PERCENT ALLOCATED!!Household income in the past 12 months
Estimate!!Families!!PERCENT ALLOCATED!!Family income in the past 12 months
Margin of Error!!Families!!PERCENT ALLOCATED!!Family income in the past 12 months
Estimate!!Families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
Margin of Error!!Families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
Estimate!!Married-couple families!!Total
Margin of Error!!Married-couple families!!Total
Estimate!!Married-couple families!!Total!!Less than $10,000
Margin of Error!!Married-couple families!!Total!!Less than $10,000
Estimate!!Married-couple families!!Total!!$10,000 to $14,999
Margin of Error!!Married-couple families!!Total!!$10,000 to $14,999
Estimate!!Married-couple families!!Total!!$15,000 to $24,999
Margin of Error!!Married-couple families!!Total!!$15,000 to $24,999
Estimate!!Married-couple families!!Total!!$25,000 to $34,999
Margin of Error!!Married-couple families!!Total!!$25,000 to $34,999
Estimate!!Married-couple families!!Total!!$35,000 to $49,999
Margin of Error!!Married-couple families!!Total!!$35,000 to $49,999
Estimate!!Married-couple families!!Total!!$50,000 to $74,999
Margin of Error!!Married-couple families!!Total!!$50,000 to $74,999
Estimate!!Married-couple families!!Total!!$75,000 to $99,999
Margin of Error!!Married-couple families!!Total!!$75,000 to $99,999
Estimate!!Married-couple families!!Total!!$100,000 to $149,999
Margin of Error!!Married-couple families!!Total!!$100,000 to $149,999
Estimate!!Married-couple families!!Total!!$150,000 to $199,999
Margin of Error!!Married-couple families!!Total!!$150,000 to $199,999
Estimate!!Married-couple families!!Total!!$200,000 or more
Margin of Error!!Married-couple families!!Total!!$200,000 or more
Estimate!!Married-couple families!!Median income (dollars)
Margin of Error!!Married-couple families!!Median income (dollars)
Estimate!!Married-couple families!!Mean income (dollars)
Margin of Error!!Married-couple families!!Mean income (dollars)
Estimate!!Married-couple families!!PERCENT ALLOCATED!!Household income in the past 12 months
Margin of Error!!Married-couple families!!PERCENT ALLOCATED!!Household income in the past 12 months
Estimate!!Married-couple families!!PERCENT ALLOCATED!!Family income in the past 12 months
Margin of Error!!Married-couple families!!PERCENT ALLOCATED!!Family income in the past 12 months
Estimate!!Married-couple families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
Margin of Error!!Married-couple families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
Estimate!!Nonfamily households!!Total
Margin of Error!!Nonfamily households!!Total
Estimate!!Nonfamily households!!Total!!Less than $10,000
Margin of Error!!Nonfamily households!!Total!!Less than $10,000
Estimate!!Nonfamily households!!Total!!$10,000 to $14,999
Margin of Error!!Nonfamily households!!Total!!$10,000 to $14,999
Estimate!!Nonfamily households!!Total!!$15,000 to $24,999
Margin of Error!!Nonfamily households!!Total!!$15,000 to $24,999
Estimate!!Nonfamily households!!Total!!$25,000 to $34,999
Margin of Error!!Nonfamily households!!Total!!$25,000 to $34,999
Estimate!!Nonfamily households!!Total!!$35,000 to $49,999
Margin of Error!!Nonfamily households!!Total!!$35,000 to $49,999
Estimate!!Nonfamily households!!Total!!$50,000 to $74,999
Margin of Error!!Nonfamily households!!Total!!$50,000 to $74,999
Estimate!!Nonfamily households!!Total!!$75,000 to $99,999
Margin of Error!!Nonfamily households!!Total!!$75,000 to $99,999
Estimate!!Nonfamily households!!Total!!$100,000 to $149,999
Margin of Error!!Nonfamily households!!Total!!$100,000 to $149,999
Estimate!!Nonfamily households!!Total!!$150,000 to $199,999
Margin of Error!!Nonfamily households!!Total!!$150,000 to $199,999
Estimate!!Nonfamily households!!Total!!$200,000 or more
Margin of Error!!Nonfamily households!!Total!!$200,000 or more
Estimate!!Nonfamily households!!Median income (dollars)
Margin of Error!!Nonfamily households!!Median income (dollars)
Estimate!!Nonfamily households!!Mean income (dollars)
Margin of Error!!Nonfamily households!!Mean income (dollars)
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months
Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months
Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months

In [5]:
df = pd.read_csv('/content/drive/MyDrive/capstone_yb/Voting ML/DATA/WA_Income.csv')
# Margin of Error
df.drop(columns=df.filter(like='Margin of Error').columns, inplace=True)
df.shape

(1784, 66)

In [6]:
import numpy as np
# (X) >> NaN Change
df.replace('(X)', np.nan, inplace=True)
# ('N') >> NaN Change
df.replace('N', np.nan, inplace=True)
missing_values = df.isnull().sum() / len(df)
print(missing_values)

# Missing Ration is not 0
missing_columns = missing_values[missing_values > 0]

print("Missing Ratio:")
print(missing_columns)

Geography                                                                                    0.000000
Geographic Area Name                                                                         0.000000
Estimate!!Households!!Total                                                                  0.000000
Estimate!!Households!!Total!!Less than $10,000                                               0.000000
Estimate!!Households!!Total!!$10,000 to $14,999                                              0.000000
                                                                                               ...
Estimate!!Nonfamily households!!Median income (dollars)                                      0.000000
Estimate!!Nonfamily households!!Mean income (dollars)                                        0.002803
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months    1.000000
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months       1.000000
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months    0.000000
Length: 66, dtype: float64
Missing Ratio:
Estimate!!Households!!Mean income (dollars)                                                     0.000561
Estimate!!Households!!PERCENT ALLOCATED!!Family income in the past 12 months                    1.000000
Estimate!!Households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months                 1.000000
Estimate!!Families!!Mean income (dollars)                                                       0.002803
Estimate!!Families!!PERCENT ALLOCATED!!Household income in the past 12 months                   1.000000
Estimate!!Families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months                   1.000000
Estimate!!Married-couple families!!Mean income (dollars)                                        0.991592
Estimate!!Married-couple families!!PERCENT ALLOCATED!!Household income in the past 12 months    1.000000
Estimate!!Married-couple families!!PERCENT ALLOCATED!!Family income in the past 12 months       1.000000
Estimate!!Married-couple families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months    1.000000
Estimate!!Nonfamily households!!Mean income (dollars)                                           0.002803
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months       1.000000
Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months          1.000000
dtype: float64

In [7]:
# Delete missing columns
# Drop columns with missing ratios of 1.0
df.drop(columns=missing_columns.index, inplace=True)
df.head()

,Geography,Geographic Area Name,Estimate!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Estimate!!Households!!Total!!$10,000 to $14,999","Estimate!!Households!!Total!!$15,000 to $24,999","Estimate!!Households!!Total!!$25,000 to $34,999","Estimate!!Households!!Total!!$35,000 to $49,999","Estimate!!Households!!Total!!$50,000 to $74,999","Estimate!!Households!!Total!!$75,000 to $99,999",...,"Estimate!!Nonfamily households!!Total!!$15,000 to $24,999","Estimate!!Nonfamily households!!Total!!$25,000 to $34,999","Estimate!!Nonfamily households!!Total!!$35,000 to $49,999","Estimate!!Nonfamily households!!Total!!$50,000 to $74,999","Estimate!!Nonfamily households!!Total!!$75,000 to $99,999","Estimate!!Nonfamily households!!Total!!$100,000 to $149,999","Estimate!!Nonfamily households!!Total!!$150,000 to $199,999","Estimate!!Nonfamily households!!Total!!$200,000 or more",Estimate!!Nonfamily households!!Median income (dollars),Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
0,1400000US53001950100,"Census Tract 9501, Adams County, Washington",1099,7.6,6.2,9,11.6,13.8,18.3,13.2,...,19.2,13.8,11.3,7.1,11.7,2.9,8.8,0,27684,34.2
1,1400000US53001950200,"Census Tract 9502, Adams County, Washington",612,8.8,3.3,6.4,7.5,14.4,22.7,27.5,...,15.7,10.3,7,5.4,20,0.5,2.7,0.5,22679,38.4
2,1400000US53001950301,"Census Tract 9503.01, Adams County, Washington",501,9,0,18.2,7,26.1,17.4,11.6,...,0,27.5,22.5,0,13.7,0,26.5,0,-,36.3
3,1400000US53001950302,"Census Tract 9503.02, Adams County, Washington",621,0,6.4,13.2,6.8,9.8,32.4,10.5,...,59.8,16.1,0,12.6,0,0,0,0,21611,19.5
4,1400000US53001950303,"Census Tract 9503.03, Adams County, Washington",632,1.4,0,21.4,13.9,8.5,22,2.7,...,32.3,46.2,21.5,0,0,0,0,0,28458,67.7

In [8]:
# 'PERCENT ALLOCATED'이 포함된 열 찾기
cols_to_drop = df.columns[df.columns.str.contains('PERCENT ALLOCATED')]

# 'PERCENT ALLOCATED'이 포함된 열 삭제
df.drop(columns=cols_to_drop, inplace=True)

# 추가적으로 목록에 있는 열들 삭제
additional_cols_to_drop = [
    'Estimate!!Nonfamily households!!Total',
    'Estimate!!Married-couple families!!Total',
    'Estimate!!Families!!Total',
    'Estimate!!Households!!Total'
]

# 추가적인 열 삭제
df.drop(columns=additional_cols_to_drop, inplace=True)

In [9]:
for column in df.columns:
    print(column)

Geography
Geographic Area Name
Estimate!!Households!!Total!!Less than $10,000
Estimate!!Households!!Total!!$10,000 to $14,999
Estimate!!Households!!Total!!$15,000 to $24,999
Estimate!!Households!!Total!!$25,000 to $34,999
Estimate!!Households!!Total!!$35,000 to $49,999
Estimate!!Households!!Total!!$50,000 to $74,999
Estimate!!Households!!Total!!$75,000 to $99,999
Estimate!!Households!!Total!!$100,000 to $149,999
Estimate!!Households!!Total!!$150,000 to $199,999
Estimate!!Households!!Total!!$200,000 or more
Estimate!!Households!!Median income (dollars)
Estimate!!Families!!Total!!Less than $10,000
Estimate!!Families!!Total!!$10,000 to $14,999
Estimate!!Families!!Total!!$15,000 to $24,999
Estimate!!Families!!Total!!$25,000 to $34,999
Estimate!!Families!!Total!!$35,000 to $49,999
Estimate!!Families!!Total!!$50,000 to $74,999
Estimate!!Families!!Total!!$75,000 to $99,999
Estimate!!Families!!Total!!$100,000 to $149,999
Estimate!!Families!!Total!!$150,000 to $199,999
Estimate!!Families!!Total!!$200,000 or more
Estimate!!Families!!Median income (dollars)
Estimate!!Married-couple families!!Total!!Less than $10,000
Estimate!!Married-couple families!!Total!!$10,000 to $14,999
Estimate!!Married-couple families!!Total!!$15,000 to $24,999
Estimate!!Married-couple families!!Total!!$25,000 to $34,999
Estimate!!Married-couple families!!Total!!$35,000 to $49,999
Estimate!!Married-couple families!!Total!!$50,000 to $74,999
Estimate!!Married-couple families!!Total!!$75,000 to $99,999
Estimate!!Married-couple families!!Total!!$100,000 to $149,999
Estimate!!Married-couple families!!Total!!$150,000 to $199,999
Estimate!!Married-couple families!!Total!!$200,000 or more
Estimate!!Married-couple families!!Median income (dollars)
Estimate!!Nonfamily households!!Total!!Less than $10,000
Estimate!!Nonfamily households!!Total!!$10,000 to $14,999
Estimate!!Nonfamily households!!Total!!$15,000 to $24,999
Estimate!!Nonfamily households!!Total!!$25,000 to $34,999
Estimate!!Nonfamily households!!Total!!$35,000 to $49,999
Estimate!!Nonfamily households!!Total!!$50,000 to $74,999
Estimate!!Nonfamily households!!Total!!$75,000 to $99,999
Estimate!!Nonfamily households!!Total!!$100,000 to $149,999
Estimate!!Nonfamily households!!Total!!$150,000 to $199,999
Estimate!!Nonfamily households!!Total!!$200,000 or more
Estimate!!Nonfamily households!!Median income (dollars)

In [10]:
# Save the cleaned DataFrame to a new CSV file
df.to_csv('cleaned_income.csv', index=False)

In [11]:
# 기존 데이터프레임을 불러오는 예시 코드입니다.
df1 = pd.read_csv('/content/cleaned_income.csv')
# Replace '-' with NaN
df.replace('-', np.nan, inplace=True)

# Combine into 5 categories
df1['House Hold Less than $50,000'] = df['Estimate!!Households!!Total!!Less than $10,000'].astype(float).fillna(0) + \
                                       df['Estimate!!Households!!Total!!$10,000 to $14,999'].astype(float).fillna(0) + \
                                       df['Estimate!!Households!!Total!!$15,000 to $24,999'].astype(float).fillna(0) + \
                                       df['Estimate!!Households!!Total!!$25,000 to $34,999'].astype(float).fillna(0) + \
                                       df['Estimate!!Households!!Total!!$35,000 to $49,999'].astype(float).fillna(0)
df1['House Hold $50,000 to $99,999'] = df['Estimate!!Households!!Total!!$50,000 to $74,999'].astype(float).fillna(0) + \
                                       df['Estimate!!Households!!Total!!$75,000 to $99,999'].astype(float).fillna(0)
df1['House Hold $100,000 to $149,999'] = df['Estimate!!Households!!Total!!$100,000 to $149,999'].astype(float).fillna(0)
df1['House Hold $150,000 to $199,999'] = df['Estimate!!Households!!Total!!$150,000 to $199,999'].astype(float).fillna(0)
df1['House Hold $200,000 or more'] =df['Estimate!!Households!!Total!!$200,000 or more'].astype(float).fillna(0)

# 가족 수입 범위를 다섯 개의 범주로 결합
df1['Families Less than $50,000'] = df['Estimate!!Families!!Total!!Less than $10,000'].astype(float).fillna(0) + \
                                     df['Estimate!!Families!!Total!!$10,000 to $14,999'].astype(float).fillna(0) + \
                                     df['Estimate!!Families!!Total!!$15,000 to $24,999'].astype(float).fillna(0) + \
                                     df['Estimate!!Families!!Total!!$25,000 to $34,999'].astype(float).fillna(0) + \
                                     df['Estimate!!Families!!Total!!$35,000 to $49,999'].astype(float).fillna(0)

df1['Families $50,000 to $99,999'] = df['Estimate!!Families!!Total!!$50,000 to $74,999'].astype(float).fillna(0) + \
                                       df['Estimate!!Families!!Total!!$75,000 to $99,999'].astype(float).fillna(0)

df1['Families $100,000 to 149,999'] = df['Estimate!!Families!!Total!!$100,000 to $149,999'].astype(float).fillna(0)
df1['Families $150,000 to $199,999'] =df['Estimate!!Families!!Total!!$150,000 to $199,999'].astype(float).fillna(0)
df1['Families $200,000 or more'] =df['Estimate!!Families!!Total!!$200,000 or more'].astype(float).fillna(0)

# 결혼한 부부 가족의 수입 범위를 다섯 개의 범주로 결합
df1['Married-couple Families Less than $50,000'] = df['Estimate!!Married-couple families!!Total!!Less than $10,000'].astype(float).fillna(0) + \
                                                  df['Estimate!!Married-couple families!!Total!!$10,000 to $14,999'].astype(float).fillna(0) + \
                                                  df['Estimate!!Married-couple families!!Total!!$15,000 to $24,999'].astype(float).fillna(0) + \
                                                  df['Estimate!!Married-couple families!!Total!!$25,000 to $34,999'].astype(float).fillna(0) + \
                                                  df['Estimate!!Married-couple families!!Total!!$35,000 to $49,999'].astype(float).fillna(0)

df1['Married-couple Families $50,000 to $99,999'] = df['Estimate!!Married-couple families!!Total!!$50,000 to $74,999'].astype(float).fillna(0) + \
                                                    df['Estimate!!Married-couple families!!Total!!$75,000 to $99,999'].astype(float).fillna(0)

df1['Married-couple Families $100,000 to 149,999'] = df['Estimate!!Married-couple families!!Total!!$100,000 to $149,999'].astype(float).fillna(0)
df1['Married-couple Families $150,000 to $199,999'] = df['Estimate!!Married-couple families!!Total!!$150,000 to $199,999'].astype(float).fillna(0)
df1['Married-couple Families $200,000 or more'] = df['Estimate!!Married-couple families!!Total!!$200,000 or more'].astype(float).fillna(0)

# 비가족 가구의 수입 범위를 다섯 개의 범주로 결합
df1['Nonfamily households Less than $50,000'] = df['Estimate!!Nonfamily households!!Total!!Less than $10,000'].astype(float).fillna(0) + \
                                                df['Estimate!!Nonfamily households!!Total!!$10,000 to $14,999'].astype(float).fillna(0) + \
                                                df['Estimate!!Nonfamily households!!Total!!$15,000 to $24,999'].astype(float).fillna(0) + \
                                                df['Estimate!!Nonfamily households!!Total!!$25,000 to $34,999'].astype(float).fillna(0) + \
                                                df['Estimate!!Nonfamily households!!Total!!$35,000 to $49,999'].astype(float).fillna(0)

df1['Nonfamily households $50,000 to $99,999'] = df['Estimate!!Nonfamily households!!Total!!$50,000 to $74,999'].astype(float).fillna(0) + \
                                                 df['Estimate!!Nonfamily households!!Total!!$75,000 to $99,999'].astype(float).fillna(0)

df1['Nonfamily households $100,000 to 149,999'] = df['Estimate!!Nonfamily households!!Total!!$100,000 to $149,999'].astype(float).fillna(0)
df1['Nonfamily households $150,000 to $199,999'] = df['Estimate!!Nonfamily households!!Total!!$150,000 to $199,999'].astype(float).fillna(0)
df1['Nonfamily households $200,000 or more'] = df['Estimate!!Nonfamily households!!Total!!$200,000 or more'].astype(float).fillna(0)


# Delete original cells
# 원본 열 삭제
df1.drop(columns=['Estimate!!Households!!Total!!Less than $10,000',
                 'Estimate!!Households!!Total!!$10,000 to $14,999',
                 'Estimate!!Households!!Total!!$15,000 to $24,999',
                 'Estimate!!Households!!Total!!$25,000 to $34,999',
                 'Estimate!!Households!!Total!!$35,000 to $49,999',
                 'Estimate!!Households!!Total!!$50,000 to $74,999',
                 'Estimate!!Households!!Total!!$75,000 to $99,999',
                 'Estimate!!Households!!Total!!$100,000 to $149,999',
                 'Estimate!!Households!!Total!!$150,000 to $199,999',
                 'Estimate!!Households!!Total!!$200,000 or more',
                 'Estimate!!Families!!Total!!Less than $10,000',
                 'Estimate!!Families!!Total!!$10,000 to $14,999',
                 'Estimate!!Families!!Total!!$15,000 to $24,999',
                 'Estimate!!Families!!Total!!$25,000 to $34,999',
                 'Estimate!!Families!!Total!!$35,000 to $49,999',
                 'Estimate!!Families!!Total!!$50,000 to $74,999',
                 'Estimate!!Families!!Total!!$75,000 to $99,999',
                 'Estimate!!Families!!Total!!$100,000 to $149,999',
                 'Estimate!!Families!!Total!!$150,000 to $199,999',
                'Estimate!!Families!!Total!!$200,000 or more',
                 'Estimate!!Married-couple families!!Total!!Less than $10,000',
                 'Estimate!!Married-couple families!!Total!!$10,000 to $14,999',
                 'Estimate!!Married-couple families!!Total!!$15,000 to $24,999',
                 'Estimate!!Married-couple families!!Total!!$25,000 to $34,999',
                 'Estimate!!Married-couple families!!Total!!$35,000 to $49,999',
                 'Estimate!!Married-couple families!!Total!!$50,000 to $74,999',
                 'Estimate!!Married-couple families!!Total!!$75,000 to $99,999',
                 'Estimate!!Married-couple families!!Total!!$100,000 to $149,999',
                 'Estimate!!Married-couple families!!Total!!$150,000 to $199,999',
                'Estimate!!Married-couple families!!Total!!$200,000 or more',
                 'Estimate!!Nonfamily households!!Total!!Less than $10,000',
                 'Estimate!!Nonfamily households!!Total!!$10,000 to $14,999',
                 'Estimate!!Nonfamily households!!Total!!$15,000 to $24,999',
                 'Estimate!!Nonfamily households!!Total!!$25,000 to $34,999',
                 'Estimate!!Nonfamily households!!Total!!$35,000 to $49,999',
                 'Estimate!!Nonfamily households!!Total!!$50,000 to $74,999',
                 'Estimate!!Nonfamily households!!Total!!$75,000 to $99,999',
                 'Estimate!!Nonfamily households!!Total!!$100,000 to $149,999',
                 'Estimate!!Nonfamily households!!Total!!$150,000 to $199,999',
                 'Estimate!!Nonfamily households!!Total!!$200,000 or more',
                 ], inplace=True)


# 결과 확인
df1.head()

,Geography,Geographic Area Name,Estimate!!Households!!Median income (dollars),Estimate!!Families!!Median income (dollars),Estimate!!Married-couple families!!Median income (dollars),Estimate!!Nonfamily households!!Median income (dollars),"House Hold Less than $50,000","House Hold $50,000 to $99,999","House Hold $100,000 to $149,999","House Hold $150,000 to $199,999",...,"Married-couple Families Less than $50,000","Married-couple Families $50,000 to $99,999","Married-couple Families $100,000 to 149,999","Married-couple Families $150,000 to $199,999","Married-couple Families $200,000 or more","Nonfamily households Less than $50,000","Nonfamily households $50,000 to $99,999","Nonfamily households $100,000 to 149,999","Nonfamily households $150,000 to $199,999","Nonfamily households $200,000 or more"
0,1400000US53001950100,"Census Tract 9501, Adams County, Washington",52589,70244,73250,27684,48.2,31.5,11.5,8.2,...,24.1,43.6,21.8,8.9,1.5,69.6,18.8,2.9,8.8,0.0
1,1400000US53001950200,"Census Tract 9502, Adams County, Washington",59886,64046,70000,22679,40.4,50.2,5.7,1.6,...,19.1,67.0,9.3,1.1,3.4,70.8,25.4,0.5,2.7,0.5
2,1400000US53001950301,"Census Tract 9503.01, Adams County, Washington",39928,40425,53523,-,60.3,29.0,4.0,6.8,...,48.5,42.5,6.6,2.3,0.0,59.8,13.7,0.0,26.5,0.0
3,1400000US53001950302,"Census Tract 9503.02, Adams County, Washington",58884,60294,64875,21611,36.2,42.9,14.2,2.6,...,22.4,48.8,19.2,3.7,6.0,87.4,12.6,0.0,0.0,0.0
4,1400000US53001950303,"Census Tract 9503.03, Adams County, Washington",50915,51905,86339,28458,45.2,24.7,14.2,10.1,...,24.4,27.9,21.4,16.7,9.4,100.0,0.0,0.0,0.0,0.0

In [12]:
for column in df1.columns:
    print(column)

Geography
Geographic Area Name
Estimate!!Households!!Median income (dollars)
Estimate!!Families!!Median income (dollars)
Estimate!!Married-couple families!!Median income (dollars)
Estimate!!Nonfamily households!!Median income (dollars)
House Hold Less than $50,000
House Hold $50,000 to $99,999
House Hold $100,000 to $149,999
House Hold $150,000 to $199,999
House Hold $200,000 or more
Families Less than $50,000
Families $50,000 to $99,999
Families $100,000 to 149,999
Families $150,000 to $199,999
Families $200,000 or more
Married-couple Families Less than $50,000
Married-couple Families $50,000 to $99,999
Married-couple Families $100,000 to 149,999
Married-couple Families $150,000 to $199,999
Married-couple Families $200,000 or more
Nonfamily households Less than $50,000
Nonfamily households $50,000 to $99,999
Nonfamily households $100,000 to 149,999
Nonfamily households $150,000 to $199,999
Nonfamily households $200,000 or more

In [20]:
# Save Final File
df1.to_csv('/content/drive/MyDrive/capstone_yb/Voting ML/DATA/filtered_income.csv', index=False)